### PR TITLE
Add an error when not able to communicate with the backend.

### LINKED ISSUE #5: Détecter une coupure réseau

### LINKED ISSUE #6: Attendre le retour réseau et récupérer la situation

### PR DESCRIPTION
**Pull request by VictorRom**
Closes #6

Closes #5

### CODE REVIEW

**Comment by MrDaves24** [comment]
It doesn't work :(
It does call the API and retrieve the response when the network is back, but doesn't send the response to the frontend

**Comment by VictorRom** [comment]
When did this occure? Can you describe the way to reproduce it?

What I tested is : 
- to stop the container backend
- to stop the container astar
- to stop both

In all those case it worked, let me know so I can fix it asap.

**Comment by MrDaves24** [comment]
In the dev tools of Chrome, in the "network" tab, you can switch the option "No throttling" to "Offline" which simulates a network off  
Then you can see the retries in the network tab  
But when you switch it back on, the request works but isn't forwarded to the frontend

**Comment by VictorRom** [comment]
Thanks for the feedback, fixing it ASAP.

**Pull request merged**
